### ISSUE TITLE
Add link to talk from README.md

### ISSUE THREAD

**Issue by elliott5** [gonum/talks#4]
I'm very interested in what you guys are doing, wanted to read a talk, so it would be better if each talk were linked to from the README.md using http://go-talks.appspot.com/.

I've just had to manually set up:
[Introduction to Go and Concurrency](http://go-talks.appspot.com/github.com/gonum/talks/2015/intro_concurrency.slide#1)

So now I'll go and read your presentation...

**Comment by elliott5** [comment]
Wow, that was quick!

Probably best to also say that not all of the examples work in the playground environment (used by go-talks.appspot.com).
For example  http://go-talks.appspot.com/github.com/gonum/talks/2015/intro_concurrency.slide#21
which needs to be run locally because of the gonum library.

**Comment by elliott5** [comment]
OK, so in-order to get the talk slide deck to run locally, after downloading this repository (I used go get) and navigating to the directory which contained `intro_concurrency.slide`, I had to:

```
go install golang.org/x/tools/cmd/present
go get -u github.com/gonum/optimize
go get -u github.com/gonum/diff
present intro_concurrency.slide
```

Then all the examples work!
Maybe adding these instructions somewhere will help others, less persistent than me, view what is a fine set of slides.

**Comment by kortschak** [comment]
@btracey The way to fix this is add `//+build ignore` directives to all the currently existing example code files and then add another file that is package intro_concurrency (or whatever) and does blank imports for the required deps. Then go get github.com/gonum/talks/2015/intro_concurrency and all the deps will be pulled as well.

And at least a link to cmd/present.

I can do these if you want, or leave it up to you.

**Comment by btracey** [comment]
You can do it the first time. Then I'll see exactly what you mean and can do it the next time.

**Comment by elliott5** [comment]
@kortschak The only thing still missing from what you originally proposed is: "And at least a link to cmd/present."

I'd suggest:

```
go install golang.org/x/tools/cmd/present
go get -u github.com/gonum/talks
# navigate to the directory containing the slides you wish to view
present intro_concurrency.slide
```

**Comment by elliott5** [comment]
...obviously preceded by a sentence about having to run the slides locally for all the examples to be able to run.
